### ISSUE TITLE
no exported commands on module import

### ISSUE THREAD

**Issue by joeypiccola** [EsOsO/RRDTool#1]
importing the module does not export any commands. have tried in v4 and v5 of powershell.

**Comment by EsOsO** [comment]
It works for me:

```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        New-RRD                                            0.0        RRDTool
Function        New-RRDArea                                        0.0        RRDTool
Function        New-RRDCdef                                        0.0        RRDTool
Function        New-RRDComment                                     0.0        RRDTool
Function        New-RRDDataSource                                  0.0        RRDTool
Function        New-RRDDef                                         0.0        RRDTool
Function        New-RRDGPrint                                      0.0        RRDTool
Function        New-RRDHRule                                       0.0        RRDTool
Function        New-RRDLine                                        0.0        RRDTool
Function        New-RRDPrint                                       0.0        RRDTool
Function        New-RRDRoundRobinArchive                           0.0        RRDTool
Function        New-RRDShift                                       0.0        RRDTool
Function        New-RRDTick                                        0.0        RRDTool
Function        New-RRDVdef                                        0.0        RRDTool
Function        New-RRDVRule                                       0.0        RRDTool
Function        Out-RRDGraph                                       0.0        RRDTool
Function        Update-RRD                                         0.0        RRDTool
```

How do you import the module? (Auto import or explicit with `Import-Module`)

**Comment by joeypiccola** [comment]
`Import-Module`. Let me try it again, I thought I did my due diligence but maybe not. Feel free to close and I'll re-open if I still can't get it to work. Thanks.

**Comment by EsOsO** [comment]
Ok, thank you for the feedback

**Comment by WhiteSasha** [comment]
HI!
When i auto install module, then i see:

 New-RRD
New-RRD : The term 'New-RRD' is not recognized as the name of a cmdlet, function, script file, or operable program. Che
ck the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ New-RRD
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-RRD:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

If i use import-module: (i put module in: c:\Windows\system32\WindowsPowerShell\v1.0\Modules\RRDTool\)


get-module -ListAvailable

Manifest   1.4      RRDTool                             New-RRD New-RRDDataSource New-RRDRoundRobinArchive New-RRD...

import-module RRDTool -Verbose

VERBOSE: Loading module from path 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\RRDTool\RRDTool.psd1'.
VERBOSE: Loading module from path 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\RRDTool\RRDTool.psm1'.

after:

get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.4.1      RRDTool



No  ExportedCommands 8(.

i'm edited RRDTool.psd1

...
FunctionsToExport = @(
			"New-RRD",
			"New-RRDDataSource",
			"New-RRDRoundRobinArchive",
			"New-RRDPrint",
			"New-RRDGPrint",
			"New-RRDComment",
			"New-RRDShift",
			"New-RRDTick",
			"New-RRDHRule",
			"New-RRDVRule",
			"New-RRDLine",
			"New-RRDArea",
    		"New-RRDDef",
			"Update-RRD",
			"Out-RRDGraph",
			"New-RRDCDef",
			"New-RRDVDef"
			)...

and autoimport work fine!!!

**Comment by EsOsO** [comment]
You're right, I've fixed the psd1. At the moment only the github code is ok, I'll publish to the gallery asap.
