### ISSUE TITLE
Specify path to RRDTool on import.

### ISSUE THREAD

**Issue by Tukamok** [EsOsO/RRDTool#3]
Being able to

Import-Module -Name RRDTool -ArgumentsList <path to RRDTool> 

would be useful.

**Comment by Tukamok** [comment]
Something like:

param(
	[string]$RRDToolPath = "Undefined"
)

If ($RRDToolPath -eq "Undefined") {
	$RRDTool = '{0}\bin\rrdtool.exe' -f $PSScriptRoot
} Else {
    $RRDTool = $RRDToolPath
}

try {
    & $RRDTool | Out-Null
} catch {
    Write-Error ("$RRDTool isn't a valid location for rrdtool.exe")
    break
}

**Comment by EsOsO** [comment]
Hi @Tukamok, thanks for the suggestion, if you want to make a pull request, feel free to do so I will add it to the codebase.
