### ISSUE TITLE
when "$PSScriptRoot" include space char, occurred error on Invoke-NativeCommand in RRDTool.psm1

### ISSUE THREAD

**Issue by koichiro-h** [EsOsO/RRDTool#5]
Hi, I'm just use it.

I have noticed while using it right now.
This error is due to Invoke-Expression not being able to properly interpret the coating.
for example,  this code is received error below.

> PS C:\Users\XXXX> Invoke-Expression ("{0} info {1}" -f $env:ProgramFiles, (Join-Path -Path ([Environment]::GetFolderPath( [Environment+SpecialFolder]::MyDocuments )) -ChildPath "average.rrd" ))
> C:\Program : 用語 'C:\Program' は、コマンドレット、関数、スクリプト ファイル、または操作可能なプログラムの名前として認識されません。名前が正しく記述されていることを確認し、パスが含まれている場合はそのパスが正しいことを確認してから、再試行してください。
> 発生場所 行:1 文字:1
> \+ C:\Program Files info C:\Users\z1tg8080\Documents\average.rrd
> \+ ~~~~~~~~~~
>     \+ CategoryInfo          : ObjectNotFound: (C:\Program:String) [], CommandNotFoundException
>     \+ FullyQualifiedErrorId : CommandNotFoundException

(Sorry, Japanese output, Add the following information instead.)

> PS C:\Users\XXXX> Error[0].CategoryInfo
> 
> Category   : ObjectNotFound
> Activity   : 
> Reason     : CommandNotFoundException
> TargetName : C:\Program
> TargetType : String

The solution to the problem is, for example, for line 45 of the New-RRD function, add an ampersand first, as in this example, and enclose the path in quotation marks.
>     $cmd = "& '{0}' create {1} --step {2} --start {3} {4} {5}" -f $RRDTool, $FileName, $Step, $StartUnixTime, $DSs, $RRAs

...and more, 52 line `Write-Error $Error` was received error cause $Error is Array of All Errors history. this solution is `Write-Error $_`

Please consider.
Best regards.

**Comment by EsOsO** [comment]
i'm sorry, no longer working on this module
